### ISSUE TITLE
Bug: Cannot rename component while SQL popup open

### ISSUE THREAD

**Issue by Stephanie-Baker** [timestored/pulseui#120]
![Screenshot (2)](https://github.com/timestored/pulseui/assets/142222774/90ef9b90-dfc2-402d-ad6e-82bdf6951001)

**Comment by ryanhamilton** [comment]
+ user-ml + user-ro

**Comment by ryanhamilton** [comment]
Fix released quite a while ago. Problem had been popup tooltip.
