### ISSUE TITLE
Orderbook Heatmap Visualization

### ISSUE THREAD

**Issue by timeseries** [timestored/pulseui#123]
Hi,
I'm trialling the orderbook visualization and there's a few issues:
1. There's gaps in the chart.
2. The x axis needs a label
3. Need to show more decimal places, formatter settings similar to other chart types would be useful.

**Comment by ryanhamilton** [comment]
- Showing NaN looks bad

**Comment by ryanhamilton** [comment]
Released in 1.70
https://www.timestored.com/pulse/help/chart-depthmap
