### ISSUE TITLE
firewall / binding local only

### ISSUE THREAD

**Issue by ryanhamilton** [timestored/pulseui#244]
user-rd user-sit

When using Pulse with an apache proxy it would be useful to restrict it to local connections only for security reasons.

**Comment by ryanhamilton** [comment]
https://www.timestored.com/pulse/help/admin/configuration
![image](https://github.com/user-attachments/assets/14ba6107-5537-4c0d-ad32-8ac01b2d9901)

**Comment by ryanhamilton** [comment]
Tested on same network. 
127.0.0.1 = Blocked outside localhost
0.0.0.0 = Anyone can access

**Comment by timeseries** [comment]
Released 3.02
