### ISSUE TITLE
click+drag to zoom in on graph

### ISSUE THREAD

**Issue by ryanhamilton** [timestored/pulseui#50]
user-ra user-rd?
Both tried to zoom in by left clicking similar to qStudio but it had no effect.
It should support that standard zoom?

**Comment by ryanhamilton** [comment]
BLOCKED on underlying framework support: https://github.com/apache/echarts/issues/13397

**Comment by ryanhamilton** [comment]
Fixed. Click and drag to zoom in. Double click to zoom out.
Works on candlestick and timeseries.

![Uploading image.png…]()

**Comment by Jayden-McQuade-G** [comment]
Can you give an example or the implementation or link to the documentation.
